import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import { NextAuthProvider } from "./provider";


import { ReactQueryProvider } from "./ReactQueryProvider";


const poppins = Poppins({ 
  subsets: ["latin"],
  weight:['400','500','600','700','300','800'],
  display:'swap'
 });

export const metadata = {
  title: "My-App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body className={poppins.className} >
        
        <NextAuthProvider>
          <ReactQueryProvider>
          
          <div>
           
          <Navbar />
            <div>
              {children}
              </div>
              
          </div>
          </ReactQueryProvider>
        
         
        </NextAuthProvider>
        
      </body>
     
    </html>
  )
}

